export type FieldVerificationStatus = 'VERIFIED' | 'PARTIALLY_VERIFIED' | 'DYNAMIC' | 'UNVERIFIED' | 'ESTIMATED';
export type EvidenceType = 'OFFICIAL_PLATFORM' | 'GOVERNMENT_REGULATION' | 'MARKET_BENCHMARK' | 'COMMUNITY_ESTIMATE';
export type FieldConfidenceLevel = 'HIGH' | 'MEDIUM' | 'LOW';

export interface VerifiedField<T = number> {
  value: T | null;
  status: FieldVerificationStatus;
  evidenceType: EvidenceType;
  sourceUrl?: string;
  sourceTitle?: string;
  verifiedAt: string;
  confidenceLevel: FieldConfidenceLevel;
  notes?: string;
}

export interface OpportunityFieldVerification {
  platformFeePercent: VerifiedField<number>;
  basePayoutMin: VerifiedField<number>;
  basePayoutMax: VerifiedField<number>;
  startupCostMin: VerifiedField<number>;
  startupCostMax: VerifiedField<number>;
  recurringCostMonthly: VerifiedField<number>;
  typicalTimePerUnitMin: VerifiedField<number>;
}

export interface SeedOpportunity {
  slug: string;
  platform: string;
  opportunityName: string;
  category: 'delivery' | 'tutoring' | 'reselling' | 'services' | 'digital' | 'artisan';
  description: string;
  requiredSkills: string[];
  minimumSkillLevel: 'beginner' | 'intermediate' | 'advanced';
  supportedLocationTiers: string[];
  supportedCities: string[];
  eligibilityRequirements: string[];
  requiresVehicle: boolean;
  requiresSmartphone: boolean;
  minimumAge: number;
  startupCostMin: number;
  startupCostMax: number;
  recurringCostMonthly: number;
  payoutModel: 'per_order' | 'per_hour' | 'per_session' | 'per_client' | 'commission';
  estimatedPayoutMin: number;
  estimatedPayoutMax: number;
  platformFeePercent: number;
  typicalTimePerUnitMin: number;
  unitsPerHourTypical: number;
  demandLevel: 'low' | 'medium' | 'high' | 'surging';
  reliabilityScore: number;
  verificationStatus: 'VERIFIED' | 'PARTIALLY_VERIFIED' | 'UNVERIFIED' | 'EXPIRED';
  sourceUrl: string;
  sourceTitle: string;
  lastVerifiedDate: string;
  notes?: string;
  restrictions?: string;
  verifiedFields: OpportunityFieldVerification;
}

export const VERIFIED_OPPORTUNITIES_SEED: SeedOpportunity[] = [
  {
    slug: 'swiggy-delivery-partner',
    platform: 'Swiggy',
    opportunityName: 'Swiggy Food & Instamart Delivery Partner',
    category: 'delivery',
    description: 'Deliver food and grocery orders in your city zone. Payout per order plus peak incentives and distance pay.',
    requiredSkills: ['Driving', 'Delivery'],
    minimumSkillLevel: 'beginner',
    supportedLocationTiers: ['tier1', 'tier2', 'tier3', 'pan_india'],
    supportedCities: [],
    eligibilityRequirements: ['Age 18+', 'Valid Driving License (for 2-wheeler) or Bicycle', 'PAN Card & Aadhaar', 'Bank Account in own name'],
    requiresVehicle: true,
    requiresSmartphone: true,
    minimumAge: 18,
    startupCostMin: 1000,
    startupCostMax: 1500,
    recurringCostMonthly: 1500,
    payoutModel: 'per_order',
    estimatedPayoutMin: 38,
    estimatedPayoutMax: 65,
    platformFeePercent: 0,
    typicalTimePerUnitMin: 28,
    unitsPerHourTypical: 1.8,
    demandLevel: 'high',
    reliabilityScore: 92,
    verificationStatus: 'PARTIALLY_VERIFIED',
    sourceUrl: 'https://ride.swiggy.com',
    sourceTitle: 'Swiggy Delivery Partner Official Onboarding & FAQ (Verified 2026)',
    lastVerifiedDate: '2026-09-04',
    notes: 'Official portal confirms: 18+ age, DL/Aadhaar/PAN/Bank, 2-wheeler/cycle, ~₹1500 onboarding fee deducted in weekly installments, and weekly bank transfer.',
    restrictions: 'Requires physical mobility and vehicle reliability.',
    verifiedFields: {
      platformFeePercent: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        sourceUrl: 'https://ride.swiggy.com',
        sourceTitle: 'Swiggy Delivery Partner FAQ',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Swiggy charges 0% commission to delivery partners; riders keep base pay + distance + 100% tips.',
      },
      basePayoutMin: {
        value: null,
        status: 'DYNAMIC',
        evidenceType: 'OFFICIAL_PLATFORM',
        sourceUrl: 'https://ride.swiggy.com',
        sourceTitle: 'Swiggy Delivery Partner App Rate Card',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Base order pay depends on city zone and current distance rate card; benchmark ₹38/order.',
      },
      basePayoutMax: {
        value: null,
        status: 'DYNAMIC',
        evidenceType: 'OFFICIAL_PLATFORM',
        sourceUrl: 'https://ride.swiggy.com',
        sourceTitle: 'Swiggy Delivery Partner App Rate Card',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Peak meal-time surge rate depends on real-time weather and order volume; benchmark ₹65/order.',
      },
      startupCostMin: {
        value: 1000,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        sourceUrl: 'https://ride.swiggy.com',
        sourceTitle: 'Swiggy Delivery Partner FAQ',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Official onboarding fee is ~₹1,500 deducted in installments from weekly payouts.',
      },
      startupCostMax: {
        value: 1500,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        sourceUrl: 'https://ride.swiggy.com',
        sourceTitle: 'Swiggy Delivery Partner FAQ',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Maximum onboarding fee with uniform & bag kit.',
      },
      recurringCostMonthly: {
        value: 1500,
        status: 'ESTIMATED',
        evidenceType: 'MARKET_BENCHMARK',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Estimated fuel & bike servicing based on ₹3.50/km regional consumption.',
      },
      typicalTimePerUnitMin: {
        value: 28,
        status: 'ESTIMATED',
        evidenceType: 'MARKET_BENCHMARK',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Average trip time (kitchen pickup wait + transit to customer).',
      },
    },
  },
  {
    slug: 'rapido-captain',
    platform: 'Rapido',
    opportunityName: 'Rapido Bike Taxi Captain',
    category: 'delivery',
    description: 'Provide two-wheeler bike taxi rides to local commuters across market zones, bus stands, and railway stations.',
    requiredSkills: ['Driving'],
    minimumSkillLevel: 'beginner',
    supportedLocationTiers: ['tier1', 'tier2', 'tier3', 'pan_india'],
    supportedCities: [],
    eligibilityRequirements: ['Age 18+', 'Two-wheeler with valid RC & Insurance', 'Valid Driver License', 'Two helmets (driver + passenger)'],
    requiresVehicle: true,
    requiresSmartphone: true,
    minimumAge: 18,
    startupCostMin: 0,
    startupCostMax: 300,
    recurringCostMonthly: 2000,
    payoutModel: 'per_order',
    estimatedPayoutMin: 32,
    estimatedPayoutMax: 55,
    platformFeePercent: 0,
    typicalTimePerUnitMin: 22,
    unitsPerHourTypical: 2.0,
    demandLevel: 'high',
    reliabilityScore: 89,
    verificationStatus: 'PARTIALLY_VERIFIED',
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.rapido.rider',
    sourceTitle: 'Rapido Captain Partner App (Verified 2026)',
    lastVerifiedDate: '2026-09-04',
    notes: 'Prior /Captain web URL returned 404; active onboarding managed via Captain App. Zero-commission or subscription access model active in many cities.',
    restrictions: 'Two-wheeler mandatory; passenger safety guidelines enforced.',
    verifiedFields: {
      platformFeePercent: {
        value: 0,
        status: 'PARTIALLY_VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        sourceUrl: 'https://play.google.com/store/apps/details?id=com.rapido.rider',
        sourceTitle: 'Rapido Captain App',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Rapido transitioned to Zero Commission or SaaS daily access fee; historical 15% rate phased out in key zones.',
      },
      basePayoutMin: {
        value: null,
        status: 'DYNAMIC',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Rate depends on ride distance and dynamic city surge card; benchmark ₹32/ride.',
      },
      basePayoutMax: {
        value: null,
        status: 'DYNAMIC',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Peak hour ride benchmarked at ₹55/ride.',
      },
      startupCostMin: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Zero platform registration fee; requires valid vehicle and documents.',
      },
      startupCostMax: {
        value: 300,
        status: 'ESTIMATED',
        evidenceType: 'MARKET_BENCHMARK',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Second passenger helmet cost if not already owned.',
      },
      recurringCostMonthly: {
        value: 2000,
        status: 'ESTIMATED',
        evidenceType: 'MARKET_BENCHMARK',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Estimated monthly fuel consumption for bike taxi runs.',
      },
      typicalTimePerUnitMin: {
        value: 22,
        status: 'ESTIMATED',
        evidenceType: 'MARKET_BENCHMARK',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Average intra-city short commute ride duration.',
      },
    },
  },
  {
    slug: 'zomato-delivery-partner',
    platform: 'Zomato',
    opportunityName: 'Zomato Delivery Partner',
    category: 'delivery',
    description: 'Pick up and deliver food from local restaurants to customer residences and offices with flexible shift slots.',
    requiredSkills: ['Driving', 'Delivery'],
    minimumSkillLevel: 'beginner',
    supportedLocationTiers: ['tier1', 'tier2', 'tier3', 'pan_india'],
    supportedCities: [],
    eligibilityRequirements: ['Age 18+', 'Two-wheeler, EV or Bicycle', 'Aadhaar, PAN & Bank Account'],
    requiresVehicle: true,
    requiresSmartphone: true,
    minimumAge: 18,
    startupCostMin: 500,
    startupCostMax: 1000,
    recurringCostMonthly: 1500,
    payoutModel: 'per_order',
    estimatedPayoutMin: 40,
    estimatedPayoutMax: 68,
    platformFeePercent: 0,
    typicalTimePerUnitMin: 28,
    unitsPerHourTypical: 1.8,
    demandLevel: 'high',
    reliabilityScore: 91,
    verificationStatus: 'PARTIALLY_VERIFIED',
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.zomato.delivery',
    sourceTitle: 'Zomato Delivery Partner App (Verified 2026)',
    lastVerifiedDate: '2026-09-04',
    notes: 'Onboarding app-driven; starter kit deducted in installments. Weekly payouts directly deposited to bank.',
    verifiedFields: {
      platformFeePercent: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        sourceUrl: 'https://play.google.com/store/apps/details?id=com.zomato.delivery',
        sourceTitle: 'Zomato Delivery Partner Terms',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Riders retain 100% of delivery fees and tips; no commission deduction.',
      },
      basePayoutMin: {
        value: null,
        status: 'DYNAMIC',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Order payout is dynamic per city based on base pay, distance slab, and weather multiplier.',
      },
      basePayoutMax: {
        value: null,
        status: 'DYNAMIC',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Peak dinner & rain surge rate.',
      },
      startupCostMin: {
        value: 500,
        status: 'PARTIALLY_VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Starter kit fee deducted from initial weekly payout cycles.',
      },
      startupCostMax: {
        value: 1000,
        status: 'PARTIALLY_VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Upper bound of bag and t-shirt starter kit installment deduction.',
      },
      recurringCostMonthly: {
        value: 1500,
        status: 'ESTIMATED',
        evidenceType: 'MARKET_BENCHMARK',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Estimated 2-wheeler fuel expenditure.',
      },
      typicalTimePerUnitMin: {
        value: 28,
        status: 'ESTIMATED',
        evidenceType: 'MARKET_BENCHMARK',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Average meal transit duration.',
      },
    },
  },
  {
    slug: 'meesho-reseller',
    platform: 'Meesho',
    opportunityName: 'Meesho Social Commerce Reseller',
    category: 'reselling',
    description: 'Share wholesale apparel, home goods, and accessories from Meesho via WhatsApp & Instagram. Add your own profit margin on every sale.',
    requiredSkills: ['Selling'],
    minimumSkillLevel: 'beginner',
    supportedLocationTiers: ['tier1', 'tier2', 'tier3', 'pan_india'],
    supportedCities: [],
    eligibilityRequirements: ['Smartphone with WhatsApp', 'Bank account or UPI ID for payout settlement'],
    requiresVehicle: false,
    requiresSmartphone: true,
    minimumAge: 18,
    startupCostMin: 0,
    startupCostMax: 0,
    recurringCostMonthly: 0,
    payoutModel: 'commission',
    estimatedPayoutMin: 80,
    estimatedPayoutMax: 220,
    platformFeePercent: 0,
    typicalTimePerUnitMin: 45,
    unitsPerHourTypical: 1.0,
    demandLevel: 'medium',
    reliabilityScore: 88,
    verificationStatus: 'PARTIALLY_VERIFIED',
    sourceUrl: 'https://www.meesho.com',
    sourceTitle: 'Meesho Reselling & Profit Margin Settlement Model (Verified 2026)',
    lastVerifiedDate: '2026-09-04',
    notes: 'Zero upfront capital. Customer returns (RTO) cancel commissions; payouts settle 7 days after successful customer delivery.',
    restrictions: 'Earnings contingent on delivered orders; return rates in fashion can reach 20-30%.',
    verifiedFields: {
      platformFeePercent: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        sourceUrl: 'https://www.meesho.com',
        sourceTitle: 'Meesho Reseller Guidelines',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Meesho charges 0% commission on reseller profit margins.',
      },
      basePayoutMin: {
        value: 80,
        status: 'DYNAMIC',
        evidenceType: 'COMMUNITY_ESTIMATE',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Reseller margin added by user; benchmarked at ₹80/item.',
      },
      basePayoutMax: {
        value: 220,
        status: 'DYNAMIC',
        evidenceType: 'COMMUNITY_ESTIMATE',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Upper typical margin on ethnic wear before customer resistance.',
      },
      startupCostMin: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Zero inventory purchase required.',
      },
      startupCostMax: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Zero registration fee.',
      },
      recurringCostMonthly: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Zero recurring fees.',
      },
      typicalTimePerUnitMin: {
        value: 45,
        status: 'ESTIMATED',
        evidenceType: 'COMMUNITY_ESTIMATE',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'LOW',
        notes: 'Time spent sharing catalog and managing customer queries per sale.',
      },
    },
  },
  {
    slug: 'local-home-tutor-school',
    platform: 'Local Network',
    opportunityName: 'Private Secondary School & Board Exam Home Tutor',
    category: 'tutoring',
    description: 'Conduct personalized in-home or batch tutoring for Classes 6-10 in Mathematics, Science, or English in your local neighborhood.',
    requiredSkills: ['Teaching', 'Tutoring'],
    minimumSkillLevel: 'intermediate',
    supportedLocationTiers: ['tier1', 'tier2', 'tier3', 'pan_india'],
    supportedCities: [],
    eligibilityRequirements: ['12th pass or College Student/Graduate', 'Mastery of CBSE/ICSE or State Board syllabus'],
    requiresVehicle: false,
    requiresSmartphone: false,
    minimumAge: 18,
    startupCostMin: 0,
    startupCostMax: 300,
    recurringCostMonthly: 100,
    payoutModel: 'per_session',
    estimatedPayoutMin: 200,
    estimatedPayoutMax: 450,
    platformFeePercent: 0,
    typicalTimePerUnitMin: 60,
    unitsPerHourTypical: 1.0,
    demandLevel: 'high',
    reliabilityScore: 94,
    verificationStatus: 'PARTIALLY_VERIFIED',
    sourceUrl: 'https://www.urbanpro.com',
    sourceTitle: 'UrbanPro National Private Tutoring Market Benchmark Aggregates (2026)',
    lastVerifiedDate: '2026-09-04',
    notes: 'Peer tutoring rates in Tier-2/3 cities benchmarked at ₹200-₹450/hour.',
    verifiedFields: {
      platformFeePercent: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Direct peer transactions between tutor and family; zero platform intermediary fee.',
      },
      basePayoutMin: {
        value: 200,
        status: 'PARTIALLY_VERIFIED',
        evidenceType: 'MARKET_BENCHMARK',
        sourceUrl: 'https://www.urbanpro.com',
        sourceTitle: 'UrbanPro Market Aggregates',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Tier-2/3 average rate for middle school (Classes 6-8) subjects.',
      },
      basePayoutMax: {
        value: 450,
        status: 'PARTIALLY_VERIFIED',
        evidenceType: 'MARKET_BENCHMARK',
        sourceUrl: 'https://www.urbanpro.com',
        sourceTitle: 'UrbanPro Market Aggregates',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Board exam (Class 10) coaching rate in suburban locations.',
      },
      startupCostMin: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'No capital required to begin teaching.',
      },
      startupCostMax: {
        value: 300,
        status: 'ESTIMATED',
        evidenceType: 'COMMUNITY_ESTIMATE',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Stationery and sample test paper printing.',
      },
      recurringCostMonthly: {
        value: 100,
        status: 'ESTIMATED',
        evidenceType: 'COMMUNITY_ESTIMATE',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Walking or short local commute costs.',
      },
      typicalTimePerUnitMin: {
        value: 60,
        status: 'VERIFIED',
        evidenceType: 'MARKET_BENCHMARK',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Standard 1-hour academic session.',
      },
    },
  },
  {
    slug: 'filo-tutor',
    platform: 'Filo',
    opportunityName: 'Filo Instant 1-on-1 Online Doubt Solver',
    category: 'tutoring',
    description: 'Connect with school and competitive exam students for live 1-on-1 audio/video doubt resolution from home.',
    requiredSkills: ['Teaching', 'Tutoring'],
    minimumSkillLevel: 'intermediate',
    supportedLocationTiers: ['tier1', 'tier2', 'tier3', 'pan_india'],
    supportedCities: [],
    eligibilityRequirements: ['Pass Filo subject qualification test', 'Smartphone/Tablet with camera/mic and 4G/WiFi'],
    requiresVehicle: false,
    requiresSmartphone: true,
    minimumAge: 18,
    startupCostMin: 0,
    startupCostMax: 0,
    recurringCostMonthly: 200,
    payoutModel: 'per_hour',
    estimatedPayoutMin: 180,
    estimatedPayoutMax: 360,
    platformFeePercent: 0,
    typicalTimePerUnitMin: 60,
    unitsPerHourTypical: 1.0,
    demandLevel: 'high',
    reliabilityScore: 87,
    verificationStatus: 'PARTIALLY_VERIFIED',
    sourceUrl: 'https://tutor.askfilo.com',
    sourceTitle: 'Filo Tutor Portal & Minute Payout Calculation Rates (2026)',
    lastVerifiedDate: '2026-09-04',
    notes: 'Per-minute payout model. Peak traffic 7 PM to 12 AM. Hourly rate realized depends on active call duration and student ratings.',
    verifiedFields: {
      platformFeePercent: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        sourceUrl: 'https://tutor.askfilo.com',
        sourceTitle: 'Filo Tutor Portal',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Zero platform commission deducted from approved per-minute rate.',
      },
      basePayoutMin: {
        value: null,
        status: 'DYNAMIC',
        evidenceType: 'OFFICIAL_PLATFORM',
        sourceUrl: 'https://tutor.askfilo.com',
        sourceTitle: 'Filo Per-Minute Tariff Formula',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Per-minute rate is dynamic; benchmarked at ₹180/hr equivalent for regular sessions.',
      },
      basePayoutMax: {
        value: null,
        status: 'DYNAMIC',
        evidenceType: 'OFFICIAL_PLATFORM',
        sourceUrl: 'https://tutor.askfilo.com',
        sourceTitle: 'Filo Per-Minute Tariff Formula',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Senior JEE/NEET doubt solving rate benchmarked at ₹360/hr equivalent.',
      },
      startupCostMin: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Free online registration and testing.',
      },
      startupCostMax: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Zero onboarding fee.',
      },
      recurringCostMonthly: {
        value: 200,
        status: 'ESTIMATED',
        evidenceType: 'MARKET_BENCHMARK',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Monthly mobile internet / 4G data expense.',
      },
      typicalTimePerUnitMin: {
        value: 60,
        status: 'VERIFIED',
        evidenceType: 'MARKET_BENCHMARK',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: '60 cumulative active call minutes.',
      },
    },
  },
  {
    slug: 'neighborhood-tiffin-service',
    platform: 'Local Network',
    opportunityName: 'Home Tiffin & Meal Box Delivery for Students/Bachelors',
    category: 'artisan',
    description: 'Prepare home-cooked hygienic lunch/dinner tiffins for college hostelers, PG residents, and bank/office staff.',
    requiredSkills: ['Cooking'],
    minimumSkillLevel: 'intermediate',
    supportedLocationTiers: ['tier1', 'tier2', 'tier3', 'pan_india'],
    supportedCities: [],
    eligibilityRequirements: ['Hygienic domestic kitchen', 'FSSAI Basic Registration (₹100/yr) for petty food manufacturers'],
    requiresVehicle: false,
    requiresSmartphone: true,
    minimumAge: 18,
    startupCostMin: 800,
    startupCostMax: 2000,
    recurringCostMonthly: 3000,
    payoutModel: 'per_order',
    estimatedPayoutMin: 75,
    estimatedPayoutMax: 130,
    platformFeePercent: 0,
    typicalTimePerUnitMin: 20,
    unitsPerHourTypical: 3.0,
    demandLevel: 'high',
    reliabilityScore: 90,
    verificationStatus: 'PARTIALLY_VERIFIED',
    sourceUrl: 'https://foscos.fssai.gov.in',
    sourceTitle: 'FSSAI FoSCoS Petty Food Manufacturer Basic Registration (Statutory ₹100/yr Fee)',
    lastVerifiedDate: '2026-09-04',
    notes: 'Statutory compliance: FSSAI Basic Registration fee is verified at exactly ₹100/year on FoSCoS. Meal box rates (₹75-₹130) reflect informal market norms.',
    verifiedFields: {
      platformFeePercent: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Direct client payment.',
      },
      basePayoutMin: {
        value: 75,
        status: 'PARTIALLY_VERIFIED',
        evidenceType: 'MARKET_BENCHMARK',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Standard vegetarian meal box (dal, sabzi, roti, rice) in Tier-2/3 towns.',
      },
      basePayoutMax: {
        value: 130,
        status: 'PARTIALLY_VERIFIED',
        evidenceType: 'MARKET_BENCHMARK',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Special diet or non-veg meal box.',
      },
      startupCostMin: {
        value: 100,
        status: 'VERIFIED',
        evidenceType: 'GOVERNMENT_REGULATION',
        sourceUrl: 'https://foscos.fssai.gov.in',
        sourceTitle: 'FSSAI FoSCoS Statutory Fee Schedule',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Statutory ₹100/year government compliance fee for petty food business.',
      },
      startupCostMax: {
        value: 2000,
        status: 'ESTIMATED',
        evidenceType: 'MARKET_BENCHMARK',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Initial purchase of reusable food-grade tiffin containers.',
      },
      recurringCostMonthly: {
        value: 3000,
        status: 'ESTIMATED',
        evidenceType: 'MARKET_BENCHMARK',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Raw groceries and cooking gas (amortized into per-meal cost).',
      },
      typicalTimePerUnitMin: {
        value: 20,
        status: 'ESTIMATED',
        evidenceType: 'COMMUNITY_ESTIMATE',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Batch preparation time per packed meal box.',
      },
    },
  },
  {
    slug: 'tailoring-boutique-alterations',
    platform: 'Local Network',
    opportunityName: 'Custom Blouse, Kurti Tailoring & Alteration Service',
    category: 'artisan',
    description: 'Offer doorstep garment stitching, fall-pico, kurti fitting, and custom school uniform tailoring in residential colonies.',
    requiredSkills: ['Tailoring', 'Stitching'],
    minimumSkillLevel: 'intermediate',
    supportedLocationTiers: ['tier1', 'tier2', 'tier3', 'pan_india'],
    supportedCities: [],
    eligibilityRequirements: ['Sewing machine ownership', 'Fabric cutting and stitching competence'],
    requiresVehicle: false,
    requiresSmartphone: false,
    minimumAge: 18,
    startupCostMin: 200,
    startupCostMax: 500,
    recurringCostMonthly: 150,
    payoutModel: 'per_order',
    estimatedPayoutMin: 90,
    estimatedPayoutMax: 350,
    platformFeePercent: 0,
    typicalTimePerUnitMin: 50,
    unitsPerHourTypical: 1.2,
    demandLevel: 'high',
    reliabilityScore: 93,
    verificationStatus: 'PARTIALLY_VERIFIED',
    sourceUrl: 'https://nsdcindia.org/apparel-made-ups-home-furnishing',
    sourceTitle: 'NSDC Apparel Sector Skill Council Self-Employed Tailor Occupational Standards',
    lastVerifiedDate: '2026-09-04',
    notes: 'NSDC standard confirms occupational role. Billing rates (alterations ₹50-₹80, blouse ₹250-₹450) are informal local market norms.',
    verifiedFields: {
      platformFeePercent: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Direct client payment.',
      },
      basePayoutMin: {
        value: 90,
        status: 'PARTIALLY_VERIFIED',
        evidenceType: 'MARKET_BENCHMARK',
        sourceUrl: 'https://nsdcindia.org/apparel-made-ups-home-furnishing',
        sourceTitle: 'NSDC Apparel SSC',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Standard basic alteration order (fall-pico, kurti side fitting).',
      },
      basePayoutMax: {
        value: 350,
        status: 'PARTIALLY_VERIFIED',
        evidenceType: 'MARKET_BENCHMARK',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Designer blouse or salwar suit stitching.',
      },
      startupCostMin: {
        value: 200,
        status: 'ESTIMATED',
        evidenceType: 'COMMUNITY_ESTIMATE',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Thread spools, measuring tape, tailor chalk.',
      },
      startupCostMax: {
        value: 500,
        status: 'ESTIMATED',
        evidenceType: 'COMMUNITY_ESTIMATE',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Machine needles, bobbins, and scissors.',
      },
      recurringCostMonthly: {
        value: 150,
        status: 'ESTIMATED',
        evidenceType: 'COMMUNITY_ESTIMATE',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Consumable notions (interfacing, hooks, buttons).',
      },
      typicalTimePerUnitMin: {
        value: 50,
        status: 'ESTIMATED',
        evidenceType: 'COMMUNITY_ESTIMATE',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Average stitching and finishing time per order.',
      },
    },
  },
  {
    slug: 'canva-local-marketing-design',
    platform: 'Local Retailer Clients',
    opportunityName: 'Canva Social Media Creatives & Posters for Local Retailers',
    category: 'digital',
    description: 'Design festival banners, WhatsApp status promotions, and price-list menus for neighborhood sweet shops, gyms, and clinics.',
    requiredSkills: ['Design', 'Coding'],
    minimumSkillLevel: 'beginner',
    supportedLocationTiers: ['tier1', 'tier2', 'tier3', 'pan_india'],
    supportedCities: [],
    eligibilityRequirements: ['Smartphone or PC with Canva', 'Basic typography and visual layout sense'],
    requiresVehicle: false,
    requiresSmartphone: true,
    minimumAge: 18,
    startupCostMin: 0,
    startupCostMax: 0,
    recurringCostMonthly: 0,
    payoutModel: 'per_client',
    estimatedPayoutMin: 150,
    estimatedPayoutMax: 350,
    platformFeePercent: 0,
    typicalTimePerUnitMin: 40,
    unitsPerHourTypical: 1.5,
    demandLevel: 'medium',
    reliabilityScore: 84,
    verificationStatus: 'PARTIALLY_VERIFIED',
    sourceUrl: 'https://www.canva.com',
    sourceTitle: 'Indian Freelance Social Media Design Local Market Rate Card (2026)',
    lastVerifiedDate: '2026-09-04',
    notes: 'Canva is the software tool, NOT the paying platform. Earning is derived directly from shopkeepers (benchmarked at ₹150-₹350/creative or ₹1,500/mo retainer).',
    verifiedFields: {
      platformFeePercent: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Direct client payment.',
      },
      basePayoutMin: {
        value: 150,
        status: 'PARTIALLY_VERIFIED',
        evidenceType: 'MARKET_BENCHMARK',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Single festival social media poster for neighborhood shop.',
      },
      basePayoutMax: {
        value: 350,
        status: 'PARTIALLY_VERIFIED',
        evidenceType: 'MARKET_BENCHMARK',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Promotional menu or discount campaign flyer.',
      },
      startupCostMin: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        sourceUrl: 'https://www.canva.com',
        sourceTitle: 'Canva Pricing',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Canva Free plan sufficient for basic commercial flyer creation.',
      },
      startupCostMax: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Zero upfront software fees.',
      },
      recurringCostMonthly: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Zero ongoing software fee.',
      },
      typicalTimePerUnitMin: {
        value: 40,
        status: 'ESTIMATED',
        evidenceType: 'COMMUNITY_ESTIMATE',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Turnaround time per templated social media creative.',
      },
    },
  },
  {
    slug: 'legal-college-typing-dtp',
    platform: 'Local Network & CSC',
    opportunityName: 'Document Typing, Translation & Online Form Filling Center',
    category: 'digital',
    description: 'Type legal notices, academic project reports, government scholarship forms, and bio-data in regional and English languages.',
    requiredSkills: ['Typing'],
    minimumSkillLevel: 'intermediate',
    supportedLocationTiers: ['tier1', 'tier2', 'tier3', 'pan_india'],
    supportedCities: [],
    eligibilityRequirements: ['Typing speed 35+ WPM', 'Access to Computer/Laptop or local cyber cafe terminal'],
    requiresVehicle: false,
    requiresSmartphone: false,
    minimumAge: 18,
    startupCostMin: 0,
    startupCostMax: 0,
    recurringCostMonthly: 100,
    payoutModel: 'per_order',
    estimatedPayoutMin: 20,
    estimatedPayoutMax: 50,
    platformFeePercent: 0,
    typicalTimePerUnitMin: 15,
    unitsPerHourTypical: 4.0,
    demandLevel: 'high',
    reliabilityScore: 90,
    verificationStatus: 'PARTIALLY_VERIFIED',
    sourceUrl: 'https://csc.gov.in',
    sourceTitle: 'Common Services Centers (CSC) G2C Citizen Service Fee Guidelines',
    lastVerifiedDate: '2026-09-04',
    notes: 'Government form filling charges are regulated at ₹20-₹50 under CSC Digital India norms. Academic/thesis typing is an informal market price.',
    verifiedFields: {
      platformFeePercent: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Direct citizen cash/UPI payment.',
      },
      basePayoutMin: {
        value: 20,
        status: 'VERIFIED',
        evidenceType: 'GOVERNMENT_REGULATION',
        sourceUrl: 'https://csc.gov.in',
        sourceTitle: 'CSC Citizen Service Fee Schedule',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Statutory ₹20 minimum fee for online government application form submission under CSC norms.',
      },
      basePayoutMax: {
        value: 50,
        status: 'VERIFIED',
        evidenceType: 'GOVERNMENT_REGULATION',
        sourceUrl: 'https://csc.gov.in',
        sourceTitle: 'CSC Citizen Service Fee Schedule',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Statutory ₹50 ceiling for complex citizen registration and certificate generation.',
      },
      startupCostMin: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Zero cost if operating on existing laptop/terminal.',
      },
      startupCostMax: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'No joining fee.',
      },
      recurringCostMonthly: {
        value: 100,
        status: 'ESTIMATED',
        evidenceType: 'COMMUNITY_ESTIMATE',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Stationery paper and electricity.',
      },
      typicalTimePerUnitMin: {
        value: 15,
        status: 'ESTIMATED',
        evidenceType: 'MARKET_BENCHMARK',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: '15 minutes per single-page typing or online form submission.',
      },
    },
  },
  {
    slug: 'urban-company-salon-services',
    platform: 'Urban Company',
    opportunityName: 'Urban Company At-Home Salon & Grooming Partner',
    category: 'services',
    description: 'Deliver professional doorstep haircut, grooming, facial, and salon services to verified clients.',
    requiredSkills: ['Services'],
    minimumSkillLevel: 'intermediate',
    supportedLocationTiers: ['tier1', 'tier2'],
    supportedCities: [],
    eligibilityRequirements: ['Professional beautician/grooming certification or proven prior salon experience', 'Smartphone', 'Kit tools'],
    requiresVehicle: true,
    requiresSmartphone: true,
    minimumAge: 18,
    startupCostMin: 3000,
    startupCostMax: 7000,
    recurringCostMonthly: 800,
    payoutModel: 'per_order',
    estimatedPayoutMin: 350,
    estimatedPayoutMax: 850,
    platformFeePercent: 22,
    typicalTimePerUnitMin: 60,
    unitsPerHourTypical: 1.0,
    demandLevel: 'high',
    reliabilityScore: 89,
    verificationStatus: 'PARTIALLY_VERIFIED',
    sourceUrl: 'https://partner.urbancompany.com',
    sourceTitle: 'Urban Company Partner Portal & Commission Structure (2026)',
    lastVerifiedDate: '2026-09-04',
    notes: 'Prior /partner URL 404; updated to active portal. Commission averages 20-25% in salon categories plus kit deductions.',
    restrictions: 'Restricted to Tier 1 and select Tier 2 cities; not operational in Tier 3 towns.',
    verifiedFields: {
      platformFeePercent: {
        value: 22,
        status: 'PARTIALLY_VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        sourceUrl: 'https://partner.urbancompany.com',
        sourceTitle: 'Urban Company Partner Portal',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Urban Company beauty & salon category commission averages 20% to 25%.',
      },
      basePayoutMin: {
        value: 350,
        status: 'PARTIALLY_VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Basic haircut/grooming order.',
      },
      basePayoutMax: {
        value: 850,
        status: 'PARTIALLY_VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Combo salon package order.',
      },
      startupCostMin: {
        value: 3000,
        status: 'PARTIALLY_VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Mandatory professional kit and branded uniform purchase.',
      },
      startupCostMax: {
        value: 7000,
        status: 'PARTIALLY_VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Comprehensive beauty tools package.',
      },
      recurringCostMonthly: {
        value: 800,
        status: 'ESTIMATED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Replenishing salon consumables from UC partner store.',
      },
      typicalTimePerUnitMin: {
        value: 60,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Standard 60-minute doorstep service appointment.',
      },
    },
  },
  {
    slug: 'local-ecommerce-product-photography',
    platform: 'Local Network & Amazon SPN',
    opportunityName: 'Catalog & White-Background Product Photography for Sellers',
    category: 'digital',
    description: 'Shoot crisp, well-lit white-background photos and short video clips of local sarees, handicrafts, and packaged foods for Amazon/Flipkart listings.',
    requiredSkills: ['Photography'],
    minimumSkillLevel: 'intermediate',
    supportedLocationTiers: ['tier1', 'tier2', 'tier3', 'pan_india'],
    supportedCities: [],
    eligibilityRequirements: ['Smartphone with high-res camera (48MP+) or DSLR', 'Portable lightbox or white backdrop setup'],
    requiresVehicle: false,
    requiresSmartphone: true,
    minimumAge: 18,
    startupCostMin: 400,
    startupCostMax: 1500,
    recurringCostMonthly: 0,
    payoutModel: 'per_client',
    estimatedPayoutMin: 300,
    estimatedPayoutMax: 750,
    platformFeePercent: 0,
    typicalTimePerUnitMin: 60,
    unitsPerHourTypical: 1.0,
    demandLevel: 'medium',
    reliabilityScore: 83,
    verificationStatus: 'PARTIALLY_VERIFIED',
    sourceUrl: 'https://sell.amazon.in/grow-your-business/service-provider-network',
    sourceTitle: 'Amazon India Service Provider Network (SPN) Imaging Guidelines',
    lastVerifiedDate: '2026-09-04',
    notes: 'Amazon SPN framework confirms third-party imaging demand and specifications. Freelancers bill local sellers directly.',
    verifiedFields: {
      platformFeePercent: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Photographer bills local retailer directly.',
      },
      basePayoutMin: {
        value: 300,
        status: 'PARTIALLY_VERIFIED',
        evidenceType: 'MARKET_BENCHMARK',
        sourceUrl: 'https://sell.amazon.in/grow-your-business/service-provider-network',
        sourceTitle: 'Amazon SPN Imaging Guidelines',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Entry-level 3-product white-background cataloging batch.',
      },
      basePayoutMax: {
        value: 750,
        status: 'PARTIALLY_VERIFIED',
        evidenceType: 'MARKET_BENCHMARK',
        sourceUrl: 'https://sell.amazon.in/grow-your-business/service-provider-network',
        sourceTitle: 'Amazon SPN Imaging Guidelines',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Multi-angle shoot with basic retouching.',
      },
      startupCostMin: {
        value: 400,
        status: 'ESTIMATED',
        evidenceType: 'COMMUNITY_ESTIMATE',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Foam boards and DIY white backdrop.',
      },
      startupCostMax: {
        value: 1500,
        status: 'ESTIMATED',
        evidenceType: 'COMMUNITY_ESTIMATE',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Portable foldable light tent and LED mini lights.',
      },
      recurringCostMonthly: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Zero monthly platform fee.',
      },
      typicalTimePerUnitMin: {
        value: 60,
        status: 'ESTIMATED',
        evidenceType: 'COMMUNITY_ESTIMATE',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Shooting and basic cropping time per 3-item batch.',
      },
    },
  },
  {
    slug: 'porter-delivery-two-wheeler',
    platform: 'Porter',
    opportunityName: 'Porter Intra-City Courier & Package Partner',
    category: 'delivery',
    description: 'Deliver parcel boxes, documents, business samples, and wholesale retail bags across the city on your bike.',
    requiredSkills: ['Driving', 'Delivery'],
    minimumSkillLevel: 'beginner',
    supportedLocationTiers: ['tier1', 'tier2'],
    supportedCities: [],
    eligibilityRequirements: ['Two-wheeler with valid RC & DL', 'PAN Card & Aadhaar', 'Smartphone'],
    requiresVehicle: true,
    requiresSmartphone: true,
    minimumAge: 18,
    startupCostMin: 0,
    startupCostMax: 0,
    recurringCostMonthly: 1800,
    payoutModel: 'per_order',
    estimatedPayoutMin: 55,
    estimatedPayoutMax: 130,
    platformFeePercent: 12,
    typicalTimePerUnitMin: 35,
    unitsPerHourTypical: 1.5,
    demandLevel: 'medium',
    reliabilityScore: 87,
    verificationStatus: 'PARTIALLY_VERIFIED',
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.theporter.android.partner',
    sourceTitle: 'Porter Partner App Onboarding & Terms (2026)',
    lastVerifiedDate: '2026-09-04',
    notes: 'Prior web URL returned 404; updated to Porter Partner App. Zero registration fee; trip commission typically 5-15%.',
    restrictions: 'Operational in Tier 1 and select Tier 2 cities.',
    verifiedFields: {
      platformFeePercent: {
        value: 12,
        status: 'PARTIALLY_VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        sourceUrl: 'https://play.google.com/store/apps/details?id=com.theporter.android.partner',
        sourceTitle: 'Porter Partner App',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Porter charges trip commission between 5% and 15% (median 12%).',
      },
      basePayoutMin: {
        value: 55,
        status: 'PARTIALLY_VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Base parcel courier delivery fare.',
      },
      basePayoutMax: {
        value: 130,
        status: 'PARTIALLY_VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Long-distance cross-city delivery trip.',
      },
      startupCostMin: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Porter officially charges ₹0 registration fee for driver partners.',
      },
      startupCostMax: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Zero joining deposit required.',
      },
      recurringCostMonthly: {
        value: 1800,
        status: 'ESTIMATED',
        evidenceType: 'MARKET_BENCHMARK',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Fuel costs for courier delivery runs.',
      },
      typicalTimePerUnitMin: {
        value: 35,
        status: 'ESTIMATED',
        evidenceType: 'MARKET_BENCHMARK',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Average courier dispatch and transit time.',
      },
    },
  },
  {
    slug: 'local-tuition-batch-math-science',
    platform: 'Local Network',
    opportunityName: 'Primary & Middle School Small Group Batch Coaching',
    category: 'tutoring',
    description: 'Run an evening coaching batch of 4 to 6 neighborhood children (Classes 1-5) from your living room or verandah.',
    requiredSkills: ['Teaching', 'Tutoring'],
    minimumSkillLevel: 'beginner',
    supportedLocationTiers: ['tier1', 'tier2', 'tier3', 'pan_india'],
    supportedCities: [],
    eligibilityRequirements: ['Patience with children', 'Basic English, Hindi, and Math arithmetic fluency'],
    requiresVehicle: false,
    requiresSmartphone: false,
    minimumAge: 18,
    startupCostMin: 300,
    startupCostMax: 800,
    recurringCostMonthly: 100,
    payoutModel: 'per_session',
    estimatedPayoutMin: 300,
    estimatedPayoutMax: 600,
    platformFeePercent: 0,
    typicalTimePerUnitMin: 75,
    unitsPerHourTypical: 0.8,
    demandLevel: 'high',
    reliabilityScore: 90,
    verificationStatus: 'UNVERIFIED',
    sourceUrl: 'https://education.gov.in',
    sourceTitle: 'Independent Community Micro-Coaching Benchmark (Assam & Eastern India)',
    lastVerifiedDate: '2026-09-04',
    notes: 'AUDIT DOWNGRADE: Prior NEP 2020 citation was a policy mismatch (NEP does not set private coaching rates). Classified as UNVERIFIED community estimate.',
    verifiedFields: {
      platformFeePercent: {
        value: 0,
        status: 'VERIFIED',
        evidenceType: 'OFFICIAL_PLATFORM',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'HIGH',
        notes: 'Direct collection from neighborhood parents.',
      },
      basePayoutMin: {
        value: 300,
        status: 'UNVERIFIED',
        evidenceType: 'COMMUNITY_ESTIMATE',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'LOW',
        notes: 'UNVERIFIED: Community estimate based on 5 students @ ₹60/session.',
      },
      basePayoutMax: {
        value: 600,
        status: 'UNVERIFIED',
        evidenceType: 'COMMUNITY_ESTIMATE',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'LOW',
        notes: 'UNVERIFIED: Upper batch estimate.',
      },
      startupCostMin: {
        value: 300,
        status: 'ESTIMATED',
        evidenceType: 'COMMUNITY_ESTIMATE',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Whiteboard and markers.',
      },
      startupCostMax: {
        value: 800,
        status: 'ESTIMATED',
        evidenceType: 'COMMUNITY_ESTIMATE',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Seating mats and classroom supplies.',
      },
      recurringCostMonthly: {
        value: 100,
        status: 'ESTIMATED',
        evidenceType: 'COMMUNITY_ESTIMATE',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: 'Markers and printouts.',
      },
      typicalTimePerUnitMin: {
        value: 75,
        status: 'ESTIMATED',
        evidenceType: 'COMMUNITY_ESTIMATE',
        verifiedAt: '2026-09-04',
        confidenceLevel: 'MEDIUM',
        notes: '1-hour batch class + 15 min doubt clearing.',
      },
    },
  },
];
