# Production Let's Encrypt Certificate Paths
ssl_certificate /etc/letsencrypt/live/dailyearnai.com/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/dailyearnai.com/privkey.pem;
ssl_trusted_certificate /etc/letsencrypt/live/dailyearnai.com/chain.pem;
